---
title: "Min Jin Lee"
DefaultContentLanguage: en
buildFuture: true
MetaDataFormat: yaml
Paginate: 10
baseURL: "https://www.thenewdynamic.org"
enableRobotsTXT: true
googleAnalytics: ""
languageCode: en-us
blackfriday:
  extensionsmask:
    - noIntraEmphasis
config: config.yaml
theme: "hugo-base-layouts"
#themesDir: "src/themes"
#layoutDir: "src/layouts"
mediaTypes:
  text/netlify:
    delimiter: ""
    suffix: ""
outputFormats:
  HEADERS:
    baseName: _headers
    isPlainText: true
    mediatype: text/netlify
    notAlternative: true
  REDIR:
    baseName: _redirects
    isPlainText: true
    mediatype: text/netlify
    notAlternative: true
outputs:
  home:
    - HTML
    - HEADERS
    - REDIR
params:
  description: "The Official Website of Min Jin Lee"
  logo: ""
  tagsName: Type
  dev:
    fonts_path: "static/dist/Fonts"
    css_path: "static/dist/css"
    js_path: "static/dist/js"


preserveTaxonomyNames: true
related:
  includeNewer: true
  indices:
    -
      name: tool
      toLower: true
      weight: 100
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
social:
  facebook: "minjinleebooks"
  twitter: "minjinlee11"
  instagram: "lee_minjin"
taxonomies:
  category: category
  tag: tags
  tools: tools
# menu:
#   main:
#     -
#       identifier: home
#       name: "Home"
#       url: /
#       weight: 1
#     -
#       identifier: books
#       name: Books
#       url: /book/
#       weight: 10
#     -
#       identifier: news
#       name: "News & Media"
#       url: /news/
#       weight: 20
#     -
#       identifier: writing
#       name: Writing
#       url: /writing/
#       weight: 30
#     -
#       identifier: events
#       name: Events
#       url: /events/
#       weight: 40
#     -
#       identifier: events
#       name: Events
#       url: /event/
#       weight: 50
#     -
#       identifier: about
#       name: About
#       url: /about/
#       weight: 60
#     -
#       identifier: contact
#       name: Contact
#       url: /contact/
#       weight: 60
